name: Set up OpenVPN
description: Set up OpenVPN.

inputs:
  ovpn-config:
    description: OpenVPN configuration file content
    required: true
  ovpn-username:
    description: OpenVPN username
    required: true
  ovpn-password:
    description: OpenVPN password
    required: true

runs:
  using: composite
  steps:
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
      shell: bash

    - name: Write OpenVPN config
      run: |
        echo "${{ inputs.ovpn-config }}" > /tmp/client.ovpn
        chmod 600 /tmp/client.ovpn
      shell: bash

    - name: Connect
      uses: "kota65535/github-openvpn-connect-action@cd2ed8a90cc7b060dc4e001143e811b5f7ea0af5" # v3.1.0
      with:
        config_file: /tmp/client.ovpn
        username: ${{ inputs.ovpn-username }}
        password: ${{ inputs.ovpn-password }}
