name: Automatic Release
on:
  workflow_call:
    secrets:
      GITHUB_USER_TOKEN:
        description: Authentication token with write permission needed by the release bot (falls back to GITHUB_TOKEN).
        required: false

jobs:
  release:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      HAS_CONFIG: false
    steps:
      - name: Fetch semantic-release Node version
        uses: actions/checkout@v4
        with:
          repository: semantic-release/semantic-release
          sparse-checkout: |
            package.json
          sparse-checkout-cone-mode: false
          path: semantic-release-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: semantic-release-repo/package.json

      - name: Install dependencies
        run: |
          npm i -g @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/npm \
            @semantic-release/exec \
            semantic-release

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check presence of release.config.js
        run: |
          HAS_CONFIG=$(test -f "release.config.js" && echo true || echo false)
          echo "Configuration file release.config.js found: $HAS_CONFIG"
          echo "HAS_CONFIG=$HAS_CONFIG" >> $GITHUB_ENV

      - name: Checkout the workflow repository if release.config.js file is not provided
        if: ${{ env.HAS_CONFIG == 'false' }}
        uses: actions/checkout@v4
        with:
          repository: inpsyde/reusable-workflows
          path: workflow-repo

      - name: Add release.config.js file if not provided and customize it
        if: ${{ env.HAS_CONFIG == 'false' }}
        run: |
          cp ${GITHUB_WORKSPACE}/workflow-repo/templates/automatic-release/release.config.js .
          FILE=$(find . -maxdepth 1 -type f -name '*.php' -exec grep -l 'Plugin Name:' {} + | xargs -I{} basename {}) || true
          [ -n "$FILE" ] && sed "s/index\.php/$FILE/g" -i release.config.js || true

      - name: Remove the workflow repository
        if: ${{ env.HAS_CONFIG == 'false' }}
        run: |
          rm -rf workflow-repo

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_USER_TOKEN != '' && secrets.GITHUB_USER_TOKEN || secrets.GITHUB_TOKEN }}
        run: npx semantic-release
