name: Deploy with Deployer

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: Name of the target environment to load Deployer settings.
        type: string
        required: true
      VERBOSITY:
        description: Deployer command verbosity.
        required: false
        default: 'v'
        type: string
      PHP_VERSION:
        description: PHP version with which the scripts are executed.
        default: '8.2'
        required: false
        type: string
    secrets:
      COMPOSER_AUTH_JSON:
        description: Authentication for privately hosted packages and repositories as a JSON formatted object.
        required: false
      GITHUB_USER_SSH_KEY:
        description: Private SSH key to be used to reach remote destinations.
        required: false
      DEPLOY_HOSTNAME:
        description: Name of the target host.
        required: true
      DEPLOY_PORT:
        description: SSH port on the target host.
        required: true
      DEPLOY_USER:
        description: SSH user on the target host.
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GITHUB_USER_SSH_KEY }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.GITHUB_USER_SSH_KEY }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
          tools: composer, inpsyde/wp-translation-downloader
          coverage: none

      - name: Install Website
        uses: ramsey/composer-install@v3
        env:
          COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
        with:
          composer-options: --no-dev --optimize-autoloader --no-interaction

      - name: Run WordPress Translation Downloader
        run: composer wp-translation-downloader:download

      - name: Install Deployer
        uses: ramsey/composer-install@v3
        env:
          COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
        with:
          working-directory: ./deployment
          composer-options: --no-dev --optimize-autoloader --no-interaction

      - name: Configure ssh key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_HOSTNAME }} >> ~/.ssh/known_hosts

      - name: Run Deployer
        env:
          DEPLOY_HOSTNAME: ${{ secrets.DEPLOY_HOSTNAME }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          cd deployment
          ./vendor/bin/dep deploy ${{ inputs.ENVIRONMENT }} -${{ inputs.VERBOSITY}}
