name: Lint PHP

on:
  workflow_call:
    inputs:
      PHP_VERSION:
        description: PHP version with which the scripts are executed.
        default: '8.0'
        required: false
        type: string
      PHP_MATRIX:
        description: deprecated - Matrix of PHP versions as a JSON formatted object.
        required: false
        type: string
      COMPOSER_ARGS:
        description: Set of arguments passed to Composer.
        default: '--prefer-dist'
        required: false
        type: string
      LINT_ARGS:
        description: Set of arguments passed to PHP Parallel Lint.
        default: '. -e php --colors --show-deprecated'
        required: false
        type: string
      COMPOSER_DEPS_INSTALL:
        description: Whether or not to install Composer dependencies before linting.
        type: boolean
        default: false
        required: false
    secrets:
      COMPOSER_AUTH_JSON:
        description: Authentication for privately hosted packages and repositories as a JSON formatted object.
        required: false
      ENV_VARS:
        description: Additional environment variables as a JSON formatted object.
        required: false

jobs:
  lint-php:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
    strategy:
      matrix:
        php-version: ${{ inputs.PHP_MATRIX && fromJSON(inputs.PHP_MATRIX) || fromJson('["custom"]') }}
    steps:
      - name: Deprecation warning
        if: ${{ inputs.PHP_MATRIX }}
        run: echo "::warning::The inputs.PHP_MATRIX is deprecated and will be removed in future. Please use inputs.PHP_VERSION with a matrix in your consuming workflow."

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up custom environment variables
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        if: ${{ env.ENV_VARS }}
        uses: actions/github-script@v6
        with:
          script: |
            JSON
              .parse(process.env.ENV_VARS)
              .forEach(envVar => core.exportVariable(envVar.name, envVar.value));

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          # This check is being used to support inputs.PHP_MATRIX to run the strategy.matrix
          # inside of this reusable-workflow and also support inputs.PHP_VERSION and configuration
          # of a strategy.matrix in the calling workflow.
          php-version: ${{ matrix.php-version != 'custom' && matrix.php-version || inputs.PHP_VERSION }}
          tools: cs2pr, parallel-lint
          coverage: none

      - name: Install Composer dependencies
        if: ${{ inputs.COMPOSER_DEPS_INSTALL }}
        uses: ramsey/composer-install@v2
        with:
          composer-options: ${{ inputs.COMPOSER_ARGS }}

      - name: Run PHP lint check
        run: parallel-lint ${{ inputs.LINT_ARGS }} --checkstyle | cs2pr
