name: Static WP Scripts Quality Assurance

on:
  workflow_call:
    inputs:
      NPM_REGISTRY_DOMAIN:
        description: Domain of the private npm registry.
        default: https://npm.pkg.github.com/
        required: false
        type: string
      NODE_VERSION:
        description: Node version with which the static code analysis is to be executed.
        default: 16
        required: false
        type: string
      PACKAGE_MANAGER:
        description: Package manager with which the dependencies should be installed (`npm` or `yarn`).
        default: 'yarn'
        required: false
        type: string
      NODE_OPTIONS:
        description: Space-separated list of command-line Node options.
        type: string
        default: ''
        required: false
    secrets:
      NPM_REGISTRY_TOKEN:
        description: Authentication for the private npm registry.
        required: false

jobs:
  static-wp-scripts-qa:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: ${{ inputs.NODE_OPTIONS }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          registry-url: ${{ inputs.NPM_REGISTRY_DOMAIN }}
          cache: ${{ inputs.PACKAGE_MANAGER }}

      - name: Install dependencies
        run: ${{ ((inputs.PACKAGE_MANAGER == 'yarn') && 'yarn') || 'npm install' }}

      - name: Run lint markdown docs
        run: ./node_modules/.bin/wp-scripts lint-md-docs docs/**/*.md

      - name: Run lint styles
        run: ./node_modules/.bin/wp-scripts lint-style resources/{css,scss}/**/*.{css,scss}

      - name: Run lint scripts
        run: ./node_modules/.bin/wp-scripts lint-js resources/{ts,js}/**/*{js,jsx,ts,tsx}