name: Unit tests JavaScript

on:
  workflow_call:
    inputs:
      NPM_REGISTRY_DOMAIN:
        description: Domain of the private npm registry.
        default: https://npm.pkg.github.com/
        required: false
        type: string
      NODE_VERSION:
        description: Node version with which the unit tests are to be executed.
        default: 18
        required: false
        type: string
      JEST_ARGS:
        description: Set of arguments passed to Jest.
        default: '--reporters=default --reporters=github-actions'
        required: false
        type: string
      PACKAGE_MANAGER:
        description: Package manager with which the dependencies should be installed (`npm` or `yarn`).
        default: 'npm'
        required: false
        type: string
      NODE_OPTIONS:
        description: Space-separated list of command-line Node options.
        default: ''
        required: false
        type: string
      CODECOV_FLAGS:
        description: Flags to be passed to Codecov.
        default: 'unittests'
        required: false
        type: string
    secrets:
      NPM_REGISTRY_TOKEN:
        description: Authentication for the private npm registry.
        required: false
      GITHUB_USER_EMAIL:
        description: Email address for the GitHub user configuration.
        required: false
      GITHUB_USER_NAME:
        description: Username for the GitHub user configuration.
        required: false
      GITHUB_USER_SSH_KEY:
        description: Private SSH key associated with the GitHub user passed as `GITHUB_USER_NAME`.
        required: false
      ENV_VARS:
        description: Additional environment variables as a JSON formatted object.
        required: false
      CODECOV_TOKEN:
        description: Codecov token.
        required: false

jobs:
  tests-unit-js:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up custom environment variables
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        if: ${{ env.ENV_VARS }}
        uses: actions/github-script@v7
        with:
          script: |
            JSON
              .parse(process.env.ENV_VARS)
              .forEach(envVar => core.exportVariable(envVar.name, envVar.value));

      - name: Set up Git
        uses: inpsyde/reusable-workflows/.github/actions/setup-git@main
        with:
          ssh-private-key: ${{ secrets.GITHUB_USER_SSH_KEY }}
          user-email: ${{ secrets.GITHUB_USER_EMAIL }}
          user-name: ${{ secrets.GITHUB_USER_NAME }}

      - name: Set up Node
        uses: inpsyde/reusable-workflows/.github/actions/setup-node@main
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          registry-url: ${{ inputs.NPM_REGISTRY_DOMAIN }}
          node-auth-token: ${{ secrets.NPM_REGISTRY_TOKEN }}
          node-options: ${{ inputs.NODE_OPTIONS }}
          package-manager: ${{ inputs.PACKAGE_MANAGER }}

      - name: Run Jest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          COVERAGE_ARGS=""
          [ -n "$CODECOV_TOKEN" ] && COVERAGE_ARGS="--coverage"
          ./node_modules/.bin/jest $COVERAGE_ARGS ${{ inputs.JEST_ARGS }}

      - name: Upload coverage to Codecov
        if: ${{ hashFiles('coverage/lcov.info') != '' }}
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: ${{ inputs.CODECOV_FLAGS }}
          verbose: true
