# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: wordpress.org publishing

on:
  workflow_call:
    inputs:
      SVN_REPOSITORY:
        description: "SVN repository to push a new version to. Defaults to wordpress.org"
        type: string
        default: "https://plugins.svn.wordpress.org"
        required: false

      SVN_PLUGIN_SLUG:
        description: "Plugin slug in the SVN repository. E.g. if plugin URL is https://wordpress.org/plugins/payoneer-checkout, slug is payoneer-checkout."
        type: string
        required: true

      SVN_USERNAME:
        description: "In case of wordpress.org, this is your username"
        type: string
        required: true

      SVN_PASSWORD:
        description: "In case of wordpress.org, it should be a separate SVN password, not account password. See https://make.wordpress.org/meta/handbook/tutorials-guides/svn-access/ for more details."
        type: string
        required: true

jobs:
  update_svn_from_git:
    env:
      SVN_REPO_PATH: "$HOME/svn_repository"
      SVN_TRUNK_PATH: "$SVN_REPO_PATH/trunk"
    runs-on: ubuntu-latest
    steps:
      - name: Install required tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y subversion rsync

      - name: Checkout git repository
        uses: actions/checkout@v4

      - name: Checkout SVN repository
        run: |
          set -euo pipefail
          echo "Checking out SVN repository"
          mkdir -p $SVN_REPO_PATH && cd $SVN_REPO_PATH
          svn checkout "${{ inputs.SVN_REPOSITORY }}/${{ inputs.SVN_PLUGIN_SLUG }}"

      - name: Synchronize SVN repository with Git
        run: |
          set -euo pipefail

          touch .distignore

          EXTRA_EXCLUDES=""
          if [[ ! -f "$GITHUB_WORKSPACE/readme.txt" ]]; then 
            echo "No readme.txt in the Git repository - preserving exising one";
            EXTRA_EXCLUDES="--exclude=readme.txt" 
          else
            echo ""
          fi
          
          rsync -rc \
          --delete \
          --delete-excluded \
          --exclude='.git' \
          --exclude='.svn' \
          --exclude='auth.json' \
          --exclude='.env' \
          --exclude='.env.*' \
          --exclude='composer.json' \
          --exclude='composer.lock' \
          --exclude='package.json' \
          --exclude='package-lock.json' \
          --exclude='yarn.lock' \
          --exclude='node_modules' \
          --exclude='.github' \
          --exclude='.ddev' \
          --exclude-from='.distignore' \
          $EXTRA_EXCLUDES \
          "$GITHUB_WORKSPACE/" "$SVN_TRUNK_PATH/"
